spring:
  application:
    name:
      "kfd"
  main:
    banner-mode: off

  datasource:
    url: "jdbc:postgresql://localhost:5431/postgres"
    username: "user"
    password: "password"
  jpa:
    generate-ddl: true

server:
  port: 8080


jwt:
  key: "34534645njbtgrhjnrty845jy4p5;kjml4k5m"
  access-token-expiration: 50000
  refresh-token-expiration: 200000
